# Generated by Django 4.2.30 on 2026-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
